// Code generated by thriftrw v1.8.0. DO NOT EDIT.
// @generated

package history

import "go.uber.org/thriftrw/version"

func init() {
	version.CheckCompatWithGeneratedCodeAt("1.8.0", "github.com/uber/cadence/.gen/go/history")
}
